trigger:
    batch: true
    branches:
      include: 
      - master
variables:
   buildConfiguration: 'Release'
    
stages:
  
  # Build Stage
  - stage: BuildAndTest
    jobs:
    - job: BuildAndTest
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      # Build and publish the application library
      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True
      # Publish the app as an artifact
      - publish: $(Build.StagingDirectory)
        artifact: app
        
  # Staging release
  - stage: Staging
    jobs:
    - job: Release
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      # Don't clone the repo
      - checkout: none
  
      # Download the published application artifact
      - download: current
        artifact: app
  
      # Release the app
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Visual Studio Enterprise(1)(3a5ea0a9-8105-4dce-9d6e-d52d517cee2f)'
          appType: 'webApp'
          WebAppName: 'teliosPortal'
          package: '$(Pipeline.Workspace)/**/*.zip'
      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: 'Visual Studio Enterprise(1)(3a5ea0a9-8105-4dce-9d6e-d52d517cee2f)'
          Action: 'Swap Slots'
          WebAppName: 'teliosPortal'
          ResourceGroupName: 'Telios'
          SourceSlot: 'Dev'
          PreserveVnet: true

  